image: ruby:2.3

variables:
  JEKYLL_ENV: production

test:
  stage: test
  script:
  - bundle install
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master
  - gh-pages

build:
  stage: build
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  stage: deploy
  dependencies:
  - build
  script:
  - echo "Deploying pages"
  only:
  - master

ghpages:
  stage: deploy
  dependencies:
  - build
  script:
  - git checkout gh-pages
  - git add public
  - git commit
  - git push
  only:
  - master
