# Site settings
title: We Long To Belong*
description: a quarterly zine. a quarterly concert.
url: ""

# Build settings
markdown: kramdown
permalink: /issue/:title
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: 'post'
